before_install:
  - git clone https://github.com/WordPress/WordPress
  - cd wordpress/wp-content/plugins
  - git clone --depth=50 --branch=master https://github.com/Eoxia/wpshop.git

language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly
  
script: php script/unit.script.php
matrix:
  allow_failures:
    - php: '5.6'
    - php: hhvm
    - php: '7.0'
    - php: nightly
  fast_finish: true